---
version: 2
updates:
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "brucellino"
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
     interval: "weekly"
    reviewers:
      - "brucellino"
